# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=18, default=0, max_digits=20)),
                ('inventory_number', models.CharField(max_length=8)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_departament', to='application.Departament')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=70)),
                ('home_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsiblePersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('residence_street', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('male', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='persons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_persons', to='application.ResponsiblePersons'),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_placement', to='application.Placement'),
        ),
        migrations.AddField(
            model_name='departament',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departament_placement', to='application.Placement'),
        ),
    ]
