# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20160903_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedassets',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='responsiblepersons',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
