# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-11 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20161108_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiblepersons',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='responsiblepersons',
            name='img_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
